clear all


import excel "G:\Projects\CEA vs. GBD\3. Analysis\1. Data Cleaning\2. Disease Cleaning\Original IHME GBD Data_2019.xlsx", sheet("Sheet 1") firstrow

gen strL CauseCleaned="NULL"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Non-rheumatic calcific aortic valve disease"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Non-rheumatic degenerative mitral valve disease"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Other non-rheumatic valve diseases"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Rheumatic heart disease"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Ischemic heart disease"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Ischemic stroke"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Intracerebral hemorrhage"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Subarachnoid hemorrhage"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Hypertensive heart disease"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Atrial fibrillation and flutter"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Aortic aneurysm"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Peripheral artery disease"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Endocarditis"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Other cardiovascular and circulatory diseases"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Alcoholic cardiomyopathy"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Myocarditis"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Other cardiomyopathy"
replace CauseCleaned="Cardiovascular and circulatory diseases" if cause=="Lower extremity peripheral arterial disease"
replace CauseCleaned="Cirrhosis of the liver" if cause=="Cirrhosis due to NASH"
replace CauseCleaned="Cirrhosis of the liver" if cause=="Cirrhosis and other chronic liver diseases due to alcohol use"
replace CauseCleaned="Cirrhosis of the liver" if cause=="Cirrhosis and other chronic liver diseases due to other causes"
replace CauseCleaned="Cirrhosis of the liver" if cause=="Cirrhosis and other chronic liver diseases due to hepatitis B"
replace CauseCleaned="Cirrhosis of the liver" if cause=="Cirrhosis and other chronic liver diseases due to hepatitis C"
replace CauseCleaned="Cirrhosis of the liver" if cause=="Cirrhosis and other chronic liver diseases due to NAFLD"
replace CauseCleaned="Chronic respiratory diseases" if cause=="Chronic obstructive pulmonary disease"
replace CauseCleaned="Chronic respiratory diseases" if cause=="Silicosis"
replace CauseCleaned="Chronic respiratory diseases" if cause=="Interstitial lung disease and pulmonary sarcoidosis"
replace CauseCleaned="Chronic respiratory diseases" if cause=="Other chronic respiratory diseases"
replace CauseCleaned="Chronic respiratory diseases" if cause=="Asthma"
replace CauseCleaned="Chronic respiratory diseases" if cause=="Other pneumoconiosis"
replace CauseCleaned="Chronic respiratory diseases" if cause=="Asbestosis"
replace CauseCleaned="Chronic respiratory diseases" if cause=="Coal workers pneumoconiosis"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Diabetes mellitus type 1"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Diabetes mellitus type 2"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Chronic kidney disease due to diabetes mellitus type 1"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Chronic kidney disease due to diabetes mellitus type 2"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Other gynecological diseases"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Thalassemias"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Sickle cell disorders"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="G6PD deficiency"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Other hemoglobinopathies and hemolytic anemias"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Endocrine, metabolic, blood, and immune disorders"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Chronic kidney disease due to hypertension"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Chronic kidney disease due to glomerulonephritis"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Chronic kidney disease due to other and unspecified causes"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Urinary tract infections"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Urolithiasis"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Benign prostatic hyperplasia"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Male infertility"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Acute glomerulonephritis"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Other urinary diseases"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Uterine fibroids"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Polycystic ovarian syndrome"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Female infertility"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Endometriosis"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Genital prolapse"
replace CauseCleaned="Diabetes, urogenital, blood, and endocrine diseases" if cause=="Premenstrual syndrome"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Invasive Non-typhoidal Salmonella (iNTS)"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Varicella and herpes zoster"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Tetanus"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Measles"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Upper respiratory infections"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Diarrheal diseases"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Typhoid fever"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Paratyphoid fever"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Other intestinal infectious diseases"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Lower respiratory infections"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Otitis media"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Ebola"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Pneumococcal meningitis"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="H influenzae type B meningitis"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Meningococcal meningitis"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Other meningitis"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Encephalitis"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Diphtheria"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Whooping cough"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="pertussis"
replace CauseCleaned="Diarrhea, lower respiratory infections, meningitis, and other common infectious diseases" if cause=="Meningitis"
replace CauseCleaned="Digestive diseases" if cause=="Peptic ulcer disease"
replace CauseCleaned="Digestive diseases" if cause=="Gastritis and duodenitis"
replace CauseCleaned="Digestive diseases" if cause=="Appendicitis"
replace CauseCleaned="Digestive diseases" if cause=="Paralytic ileus and intestinal obstruction"
replace CauseCleaned="Digestive diseases" if cause=="Inguinal, femoral, and abdominal hernia"
replace CauseCleaned="Digestive diseases" if cause=="Inflammatory bowel disease"
replace CauseCleaned="Digestive diseases" if cause=="Vascular intestinal disorders"
replace CauseCleaned="Digestive diseases" if cause=="Gallbladder and biliary diseases"
replace CauseCleaned="Digestive diseases" if cause=="Pancreatitis"
replace CauseCleaned="Digestive diseases" if cause=="Gastroesophageal reflux disease"
replace CauseCleaned="Digestive diseases" if cause=="Other digestive diseases"
replace CauseCleaned="Forces of nature, war, and legal intervention" if cause=="Conflict and terrorism"
replace CauseCleaned="Forces of nature, war, and legal intervention" if cause=="Exposure to forces of nature"
replace CauseCleaned="Forces of nature, war, and legal intervention" if cause=="Environmental heat and cold exposure"
replace CauseCleaned="Forces of nature, war, and legal intervention" if cause=="Executions and police conflict"
replace CauseCleaned="Forces of nature, war, and legal intervention" if cause=="Police conflict and executions"
replace CauseCleaned="HIV/AIDS and tuberculosis" if cause=="Drug-susceptible tuberculosis"
replace CauseCleaned="HIV/AIDS and tuberculosis" if cause=="Multidrug-resistant tuberculosis without extensive drug resistance"
replace CauseCleaned="HIV/AIDS and tuberculosis" if cause=="Extensively drug-resistant tuberculosis"
replace CauseCleaned="HIV/AIDS and tuberculosis" if cause=="HIV/AIDS - Drug-susceptible Tuberculosis"
replace CauseCleaned="HIV/AIDS and tuberculosis" if cause=="HIV/AIDS - Multidrug-resistant Tuberculosis without extensive drug resistance"
replace CauseCleaned="HIV/AIDS and tuberculosis" if cause=="HIV/AIDS - Extensively drug-resistant Tuberculosis"
replace CauseCleaned="HIV/AIDS and tuberculosis" if cause=="Latent tuberculosis infection"
replace CauseCleaned="HIV/AIDS and tuberculosis" if cause=="HIV/AIDS resulting in other diseases"
replace CauseCleaned="HIV/AIDS and tuberculosis" if cause=="Maternal deaths aggravated by HIV/AIDS"
replace CauseCleaned="Maternal disorders" if cause=="Indirect maternal deaths"
replace CauseCleaned="Maternal disorders" if cause=="Maternal hypertensive disorders"
replace CauseCleaned="Maternal disorders" if cause=="Other maternal disorders"
replace CauseCleaned="Maternal disorders" if cause=="Ectopic pregnancy"
replace CauseCleaned="Maternal disorders" if cause=="Maternal obstructed labor and uterine rupture"
replace CauseCleaned="Maternal disorders" if cause=="Maternal hemorrhage"
replace CauseCleaned="Maternal disorders" if cause=="Maternal sepsis and other maternal infections"
replace CauseCleaned="Maternal disorders" if cause=="Maternal abortion and miscarriage"
replace CauseCleaned="Maternal disorders" if cause=="Other direct maternal disorders"
replace CauseCleaned="Maternal disorders" if cause=="Late maternal deaths"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Schizophrenia"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Alcohol use disorders"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Opioid use disorders"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Cocaine use disorders"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Amphetamine use disorders"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Cannabis use disorders"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Other drug use disorders"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Major depressive disorder"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Bipolar disorder"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Anxiety disorders"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Anorexia nervosa"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Dysthymia"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Bulimia nervosa"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Autism spectrum disorders"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Attention-deficit/hyperactivity disorder"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Conduct disorder"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Idiopathic developmental intellectual disability"
replace CauseCleaned="Mental and behavioral disorders" if cause=="Other mental disorders"
replace CauseCleaned="Musculoskeletal disorders" if cause=="Neck pain"
replace CauseCleaned="Musculoskeletal disorders" if cause=="Gout"
replace CauseCleaned="Musculoskeletal disorders" if cause=="Other musculoskeletal disorders"
replace CauseCleaned="Musculoskeletal disorders" if cause=="Rheumatoid arthritis"
replace CauseCleaned="Musculoskeletal disorders" if cause=="Osteoarthritis"
replace CauseCleaned="Musculoskeletal disorders" if cause=="Low back pain"
replace CauseCleaned="Musculoskeletal disorders" if cause=="Age-related macular degeneration"
replace CauseCleaned="Musculoskeletal disorders" if cause=="Osteoarthritis hip"
replace CauseCleaned="Musculoskeletal disorders" if cause=="Osteoarthritis knee"
replace CauseCleaned="Musculoskeletal disorders" if cause=="Osteoarthritis hand"
replace CauseCleaned="Musculoskeletal disorders" if cause=="Osteoarthritis other"
replace CauseCleaned="N/A" if cause=="1026"
replace CauseCleaned="N/A" if cause=="1027"
replace CauseCleaned="N/A" if cause=="1028"
replace CauseCleaned="N/A" if cause=="1029"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Yellow fever"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Other neglected tropical diseases"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Rabies"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Ascariasis"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Dengue"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Trichuriasis"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Hookworm disease"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Food-borne trematodiases"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Zika virus"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Guinea worm disease"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Malaria"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Chagas disease"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Visceral leishmaniasis"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Cutaneous and mucocutaneous leishmaniasis"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="African trypanosomiasis"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Schistosomiasis"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Cysticercosis"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Cystic echinococcosis"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Lymphatic filariasis"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Onchocerciasis"
replace CauseCleaned="Neglected tropical diseases and malaria" if cause=="Trachoma"
replace CauseCleaned="Neonatal disorders" if cause=="Neonatal preterm birth"
replace CauseCleaned="Neonatal disorders" if cause=="Hemolytic disease and other neonatal jaundice"
replace CauseCleaned="Neonatal disorders" if cause=="Other neonatal disorders"
replace CauseCleaned="Neonatal disorders" if cause=="Neonatal sepsis and other neonatal infections"
replace CauseCleaned="Neonatal disorders" if cause=="Neonatal encephalopathy due to birth asphyxia and trauma"
replace CauseCleaned="Neoplasms" if cause=="Benign and in situ intestinal neoplasms"
replace CauseCleaned="Neoplasms" if cause=="Brain and central nervous system cancer"
replace CauseCleaned="Neoplasms" if cause=="Myelodysplastic, myeloproliferative, and other hematopoietic neoplasms"
replace CauseCleaned="Neoplasms" if cause=="Benign and in situ cervical and uterine neoplasms"
replace CauseCleaned="Neoplasms" if cause=="Other benign and in situ neoplasms"
replace CauseCleaned="Neoplasms" if cause=="Other leukemia"
replace CauseCleaned="Neoplasms" if cause=="Liver cancer due to NASH"
replace CauseCleaned="Neoplasms" if cause=="Multiple myeloma"
replace CauseCleaned="Neoplasms" if cause=="Other malignant neoplasms"
replace CauseCleaned="Neoplasms" if cause=="Acute lymphoid leukemia"
replace CauseCleaned="Neoplasms" if cause=="Chronic lymphoid leukemia"
replace CauseCleaned="Neoplasms" if cause=="Acute myeloid leukemia"
replace CauseCleaned="Neoplasms" if cause=="Chronic myeloid leukemia"
replace CauseCleaned="Neoplasms" if cause=="Non-melanoma skin cancer (squamous-cell carcinoma)"
replace CauseCleaned="Neoplasms" if cause=="Non-melanoma skin cancer (basal-cell carcinoma)"
replace CauseCleaned="Neoplasms" if cause=="Breast cancer"
replace CauseCleaned="Neoplasms" if cause=="Cervical cancer"
replace CauseCleaned="Neoplasms" if cause=="Uterine cancer"
replace CauseCleaned="Neoplasms" if cause=="Prostate cancer"
replace CauseCleaned="Neoplasms" if cause=="Colon and rectum cancer"
replace CauseCleaned="Neoplasms" if cause=="Lip and oral cavity cancer"
replace CauseCleaned="Neoplasms" if cause=="Nasopharynx cancer"
replace CauseCleaned="Neoplasms" if cause=="Other pharynx cancer"
replace CauseCleaned="Neoplasms" if cause=="Gallbladder and biliary tract cancer"
replace CauseCleaned="Neoplasms" if cause=="Pancreatic cancer"
replace CauseCleaned="Neoplasms" if cause=="Malignant skin melanoma"
replace CauseCleaned="Neoplasms" if cause=="Ovarian cancer"
replace CauseCleaned="Neoplasms" if cause=="Testicular cancer"
replace CauseCleaned="Neoplasms" if cause=="Kidney cancer"
replace CauseCleaned="Neoplasms" if cause=="Bladder cancer"
replace CauseCleaned="Neoplasms" if cause=="Brain and nervous system cancer"
replace CauseCleaned="Neoplasms" if cause=="Thyroid cancer"
replace CauseCleaned="Neoplasms" if cause=="Mesothelioma"
replace CauseCleaned="Neoplasms" if cause=="Hodgkin lymphoma"
replace CauseCleaned="Neoplasms" if cause=="Non-Hodgkin lymphoma"
replace CauseCleaned="Neoplasms" if cause=="Larynx cancer"
replace CauseCleaned="Neoplasms" if cause=="Tracheal, bronchus, and lung cancer"
replace CauseCleaned="Neoplasms" if cause=="Liver cancer due to alcohol use"
replace CauseCleaned="Neoplasms" if cause=="Liver cancer due to other causes"
replace CauseCleaned="Neoplasms" if cause=="Esophageal cancer"
replace CauseCleaned="Neoplasms" if cause=="Stomach cancer"
replace CauseCleaned="Neoplasms" if cause=="Liver cancer due to hepatitis B"
replace CauseCleaned="Neoplasms" if cause=="Liver cancer due to hepatitis C"
replace CauseCleaned="Neurological disorders" if cause=="Migraine"
replace CauseCleaned="Neurological disorders" if cause=="Tension-type headache"
replace CauseCleaned="Neurological disorders" if cause=="Motor neuron disease"
replace CauseCleaned="Neurological disorders" if cause=="Other neurological disorders"
replace CauseCleaned="Neurological disorders" if cause=="Alzheimer's disease and other dementias"
replace CauseCleaned="Neurological disorders" if cause=="Parkinson's disease"
replace CauseCleaned="Neurological disorders" if cause=="Epilepsy"
replace CauseCleaned="Neurological disorders" if cause=="Idiopathic epilepsy"
replace CauseCleaned="Neurological disorders" if cause=="Multiple sclerosis"
replace CauseCleaned="Nutritional Deficiencies" if cause=="Vitamin A deficiency"
replace CauseCleaned="Nutritional Deficiencies" if cause=="Dietary iron deficiency"
replace CauseCleaned="Nutritional Deficiencies" if cause=="Other nutritional deficiencies"
replace CauseCleaned="Nutritional Deficiencies" if cause=="Protein-energy malnutrition"
replace CauseCleaned="Nutritional Deficiencies" if cause=="Iodine deficiency"
replace CauseCleaned="Other communicable, maternal, neonatal, and nutritional disorders" if cause=="Acute hepatitis A"
replace CauseCleaned="Other communicable, maternal, neonatal, and nutritional disorders" if cause=="Acute hepatitis B"
replace CauseCleaned="Other communicable, maternal, neonatal, and nutritional disorders" if cause=="Acute hepatitis C"
replace CauseCleaned="Other communicable, maternal, neonatal, and nutritional disorders" if cause=="Other unspecified infectious diseases"
replace CauseCleaned="Other communicable, maternal, neonatal, and nutritional disorders" if cause=="Acute hepatitis E"
replace CauseCleaned="Other communicable, maternal, neonatal, and nutritional disorders" if cause=="Syphilis"
replace CauseCleaned="Other communicable, maternal, neonatal, and nutritional disorders" if cause=="Chlamydial infection"
replace CauseCleaned="Other communicable, maternal, neonatal, and nutritional disorders" if cause=="Gonococcal infection"
replace CauseCleaned="Other communicable, maternal, neonatal, and nutritional disorders" if cause=="Trichomoniasis"
replace CauseCleaned="Other communicable, maternal, neonatal, and nutritional disorders" if cause=="Genital herpes"
replace CauseCleaned="Other communicable, maternal, neonatal, and nutritional disorders" if cause=="Other sexually transmitted infections"
replace CauseCleaned="Other communicable, maternal, neonatal, and nutritional disorders" if cause=="Leprosy"
replace CauseCleaned="Other non-communicable diseases" if cause=="Atopic dermatitis"
replace CauseCleaned="Other non-communicable diseases" if cause=="Contact dermatitis"
replace CauseCleaned="Other non-communicable diseases" if cause=="Seborrhoeic dermatitis"
replace CauseCleaned="Other non-communicable diseases" if cause=="Decubitus ulcer"
replace CauseCleaned="Other non-communicable diseases" if cause=="Other skin and subcutaneous diseases"
replace CauseCleaned="Other non-communicable diseases" if cause=="Age-related and other hearing loss"
replace CauseCleaned="Other non-communicable diseases" if cause=="Other vision loss"
replace CauseCleaned="Other non-communicable diseases" if cause=="Other sense organ diseases"
replace CauseCleaned="Other non-communicable diseases" if cause=="Caries of deciduous teeth"
replace CauseCleaned="Other non-communicable diseases" if cause=="Caries of permanent teeth"
replace CauseCleaned="Other non-communicable diseases" if cause=="Periodontal diseases"
replace CauseCleaned="Other non-communicable diseases" if cause=="Refraction disorders"
replace CauseCleaned="Other non-communicable diseases" if cause=="Near vision loss"
replace CauseCleaned="Other non-communicable diseases" if cause=="Neural tube defects"
replace CauseCleaned="Other non-communicable diseases" if cause=="Congenital heart anomalies"
replace CauseCleaned="Other non-communicable diseases" if cause=="Orofacial clefts"
replace CauseCleaned="Other non-communicable diseases" if cause=="Down syndrome"
replace CauseCleaned="Other non-communicable diseases" if cause=="Turner syndrome"
replace CauseCleaned="Other non-communicable diseases" if cause=="Klinefelter syndrome"
replace CauseCleaned="Other non-communicable diseases" if cause=="Other congenital birth defects"
replace CauseCleaned="Other non-communicable diseases" if cause=="Psoriasis"
replace CauseCleaned="Other non-communicable diseases" if cause=="Cellulitis"
replace CauseCleaned="Other non-communicable diseases" if cause=="Pyoderma"
replace CauseCleaned="Other non-communicable diseases" if cause=="Scabies"
replace CauseCleaned="Other non-communicable diseases" if cause=="Fungal skin diseases"
replace CauseCleaned="Other non-communicable diseases" if cause=="Viral skin diseases"
replace CauseCleaned="Other non-communicable diseases" if cause=="Acne vulgaris"
replace CauseCleaned="Other non-communicable diseases" if cause=="Alopecia areata"
replace CauseCleaned="Other non-communicable diseases" if cause=="Pruritus"
replace CauseCleaned="Other non-communicable diseases" if cause=="Urticaria"
replace CauseCleaned="Other non-communicable diseases" if cause=="Other oral disorders"
replace CauseCleaned="Other non-communicable diseases" if cause=="Sudden infant death syndrome"
replace CauseCleaned="Other non-communicable diseases" if cause=="Other chromosomal abnormalities"
replace CauseCleaned="Other non-communicable diseases" if cause=="Congenital musculoskeletal and limb anomalies"
replace CauseCleaned="Other non-communicable diseases" if cause=="Urogenital congenital anomalies"
replace CauseCleaned="Other non-communicable diseases" if cause=="Digestive congenital anomalies"
replace CauseCleaned="Other non-communicable diseases" if cause=="Glaucoma"
replace CauseCleaned="Other non-communicable diseases" if cause=="Cataract"
replace CauseCleaned="Other non-communicable diseases" if cause=="Edentulism and severe tooth loss"
replace CauseCleaned="Other non-communicable diseases" if cause=="Thalassemias trait"
replace CauseCleaned="Other non-communicable diseases" if cause=="Sickle cell trait"
replace CauseCleaned="Other non-communicable diseases" if cause=="G6PD trait"
replace CauseCleaned="Self-harm and interpersonal violence" if cause=="Sexual violence"
replace CauseCleaned="Self-harm and interpersonal violence" if cause=="Self-harm by firearm"
replace CauseCleaned="Self-harm and interpersonal violence" if cause=="Self-harm by other specified means"
replace CauseCleaned="Self-harm and interpersonal violence" if cause=="Physical violence by firearm"
replace CauseCleaned="Self-harm and interpersonal violence" if cause=="Physical violence by sharp object"
replace CauseCleaned="Self-harm and interpersonal violence" if cause=="Physical violence by other means"
replace CauseCleaned="Transport injuries" if cause=="Pedestrian road injuries"
replace CauseCleaned="Transport injuries" if cause=="Cyclist road injuries"
replace CauseCleaned="Transport injuries" if cause=="Motorcyclist road injuries"
replace CauseCleaned="Transport injuries" if cause=="Motor vehicle road injuries"
replace CauseCleaned="Transport injuries" if cause=="Other road injuries"
replace CauseCleaned="Transport injuries" if cause=="Other transport injuries"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Falls"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Drowning"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Fire, heat, and hot substances"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Poisoning by carbon monoxide"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Poisoning by other means"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Unintentional firearm injuries"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Other exposure to mechanical forces"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Venomous animal contact"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Non-venomous animal contact"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Foreign body in eyes"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Foreign body in other body part"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Other unintentional injuries"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Adverse effects of medical treatment"
replace CauseCleaned="Unintentional injuries other than transport injuries" if cause=="Pulmonary aspiration and foreign body in airway"

drop measure year

collapse (sum) DALY upper lower , by (location CauseCleaned)


export excel using "G:\Projects\CEA vs. GBD\3. Analysis\1. Data Cleaning\IHME DALYs_2019.xlsx", firstrow(variables) nolabel replace
